{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Key-value хранилище, FAQ.ipynb",
      "provenance": [],
      "authorship_tag": "ABX9TyNTG+MB5qRSRdlLvstCUDy3",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/pythonkvs/seminars/blob/main/homeworks/Key_value_%D1%85%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B5_FAQ.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "t2ZwSKS4-OFD"
      },
      "source": [
        "**FAQ. Частые вопросы, возникающие при решении данного задания.**  \n",
        "\n",
        "https://www.coursera.org/learn/diving-in-python/discussions/all/threads/yE8NqaW8Su2PDamlvBrt8Q\n",
        "\n",
        "1. Реализовал задачу с помощью модуля 'click'. Решение не принимается. Хотя в задаче не сказано, что решение должно быть только с argparse.  Грейдер вернул ошибку - **ModuleNotFoundError: No module named 'click'**\n",
        "\n",
        "**Сlick** - сторонний модуль, не входящий в стандартную библиотеку **Python**. Если для решения необходимо использование сторонних библиотек, об этом явно указывается в описании заданий. В противном случае необходимо использовать только модули стандартной библиотеки. В описании задания есть прямое указание на использование модуля agrparse - \"**Для работы с аргументами командной строки используйте модуль argparse.**\"\n",
        "\n",
        "2. Получаю ошибку - **Total tests: 22. Tests failed: 22, Errors: 0. Total time: 1.841. Failed test - test_1. E AssertionError: Тест 1.1. Запрос на получение ключа для случая, когда файл хранилища storage.data не существует на файловой системе, завершился с ошибкой...** Не совсем понимаю, что требует грейдер, локально все работает. \n",
        "\n",
        "Проверьте, что ваша реализация скрипта правильно обрабатывает случай \"первого запуска\", а именно запроса на получения данных по ключу (когда файл **storage.data** еще не существует). Чтобы воспроизвести эту ситуацию локально, удалите файл **storage.data** с файловой системы и запустите ваш скрипт на получение данных по ключу.\n",
        "\n",
        "```bash\n",
        "$ storage.py --key key_name\n",
        "```\n",
        "\n",
        "Такой запрос должен обрабатываться корректно (из описания задания - **\"Если значений по ключу не было найдено, выведите пустую строку или None.\"**) и не вызвать сообщений об ошибке.\n",
        "\n",
        "Так же стоит проверить правильность пути по которому создается файл хранилища (файл должен создаваться в директории, возвращаемой вызовом **tempfile.gettempdir()**) и само название файла (должен называться **storage.data**). \n",
        "\n",
        "Еще одной причиной возникновения этой ошибки может быть не правильный выбор режима открытия файла  **\"r+\"** (обновления (чтение и запись)) при создании файла. Он подразумевает, что открываемый файл уже существует на файловой системе.  Используйте другие режимы или проверяйте перед открытием существует ли файл. См [open](https://docs.python.org/3.3/library/functions.html#open) и [os.path.exists](https://docs.python.org/3.3/library/os.path.html?highlight=os.path.exists#os.path.exists).\n",
        "\n",
        "3. Получаю ошибку - **\"Total tests: 22. Tests failed: 20, Errors: 0. Total time: 2.675. Failed test - test_2. E AssertionError: Тест 2.3. Запрос на сохранение значения по ключу для случая, когда файл хранилища storage.data не существует на файловой системе, должен создавать файл хранилища\".** Не понял чего хочет тест от меня.\n",
        "\n",
        "Грейдер требует от вашего решения выполнения условий из описания задания - **\"Данные будут сохраняться в файле storage.data. ..... Файл следует создавать с помощью модуля tempfile. <пример кода>\"**, о чем вам прямо указано в сообщении об ошибке - **\" Запрос на сохранение значения по ключу для случая, когда файл хранилища storage.data не существует на файловой системе, должен создавать файл хранилища.\"** . Проверьте, что: файл реально создается на файловой системе, путь до него получен с помощью **tempfile.gettempdir()** и файл называется **storage.data**.\n",
        "\n",
        "4. Вылезает такая ошибка: **\"Total tests: 22. Tests failed: 19, Errors: 0. Total time: 2.663. Failed test - test_3. E AssertionError: Тест 3.2. В хранилище сохранено одно значение по ключу (key=number, value=3). Запрос на получение значения по существующему ключу вывел на печать не верное значение: ['3'] assert \"['3']\" == '3' - ['3'] + 3\".**   Не пойму как это можно исправить.\n",
        "\n",
        "Из описания задания - **\"При выводе на печать, значения выводятся в порядке их добавления в хранилище. Формат вывода на печать для нескольких значений: value_1, val\".** Вы выводите список на печать, по этой причине получаете вывод в квадратных скобках (строковое представление списка). Как вариант решения проблемы можно предложить:\n",
        "\n",
        "1. Попробуйте перед выводом создать строку, содержащую элементы списка (цикл + конкатенация строк)\n",
        "\n",
        "2. Попробуйте используйте метод строк join.\n",
        "\n",
        "3. Попробуйте использовать ключевой аргумент функции print - \"sep\" + операцию распаковки списка с помощью \"* \".\n",
        "\n",
        "4. Попробуйте использовать цикл и функцию print с ключевым аргументом end.\n",
        "\n",
        "Решение проблемы быстро находится [поиском](https://www.google.ru/search?q=python+%D0%B2%D1%8B%D0%B2%D0%B5%D1%81%D1%82%D0%B8+%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B+%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0+%D1%87%D0%B5%D1%80%D0%B5%D0%B7+%D0%BF%D1%80%D0%BE%D0%B1%D0%B5%D0%BB&oq=python+%D0%B2%D1%8B%D0%B2%D0%B5%D1%81%D1%82%D0%B8+%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B+%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0). \n",
        "\n",
        "5. Грейдер вернул ошибку - **\"В хранилище сохранено два значения: 1, 1 по ключу: key=number. Запрос на получение значений по ключу: key=number вывел на печать не верные значения : 1,1.\"** Правильно ли я понимаю, что должно было быть выведено одно значение 1, т.е. при добавлении того же ключа и того же значения, ничего не должно изменяться?\n",
        "\n",
        "Нет, значения, сохраняемые по одному ключу, не уникальны (могут быть одинаковыми). Проверьте правильность формата вывода значений (через запятую + пробел).\n",
        "\n",
        "6. Грейдер вернул ошибку - **\"Тест 2.2. Запрос на сохранение значения по ключу для случая, когда файл хранилища storage.data не существует на файловой системе, должен выводить на печать пустую строку. Ваш вывод: key, value.\"** Что делаю не так?\n",
        "\n",
        "Из описания задания - **\"Если передано только имя ключа, происходит чтение файла хранилища и вывод на печать значений, которые были сохранены по данному ключу. \".** Вывод данных осуществляется только при команде на получение данных, упоминаний о том, что при команде на сохранение данных в хранилище нужно выводить какие-либо сообщения на печать - нет. Так же в описании задания есть пример работы. В строках 1, 5, 6 выполнены команды на сохранение данных в хранилище. Вы можете видеть, что никаких сообщений при этом не выводится. "
      ]
    }
  ]
}